config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  devise_for :doctors, controllers: {
    sessions: 'doctors/sessions'
  }

  devise_for :patients, controllers: {
    registrations: 'patients/registrations',
    sessions: 'patients/sessions'
  }

  resources :patients, only: %i[show edit update] do
    resources :appointments, only: :index
  end

  resources :doctors, only: %i[show index] do
    resources :appointments do
      collection do
        get 'available_hours', to: 'appointments#available_hours'
      end
    end
    resources :patients, only: :index
  end
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="container">
    <div class="alert alert-dismissible fade show <%= key == "notice" ? "alert-primary" : "alert-danger" %>" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/shared/_login_form.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h2 class="text-center mb-4"><%= t("shared.sessions.new.login_#{type}") %></h2>

    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <%= render 'shared/error_messages', resource: resource %>
      <div class="mb-3">
        <%= f.label :phone_number, class: 'form-label' %><br/>
        <div class="input-group">
          <div class="input-group-text">+380</div>
          <%= f.telephone_field :phone_number, autocomplete: 'phone_number', class: 'form-control' %>
        </div>
      </div>

      <div class="mb-3">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, autocomplete: 'new-password', class: 'form-control' %>
      </div>

      <div class="actions text-center">
        <%= f.submit t('shared.sessions.new.login_btn'), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <%= link_to root_path, class: 'navbar-brand', aria: { current: 'page' } do %>
      <%= image_tag('logo.svg', height: 24, class: 'd-inline-block align-text-top') %>
      <%= t('navigation.brand') %>
    <% end %>

    <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to t('navigation.doctors'), doctors_path, class: 'nav-link' %>
        </li>
      </ul>

      <ul class="navbar-nav ml-md-auto mb-2 mb-lg-0">
        <% if current_patient || current_doctor %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
               role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "#{t('navigation.patient')} #{current_patient.last_name}" if current_patient %>
              <%= "#{t('navigation.doctor')} #{current_doctor.last_name}" if current_doctor %>

            </a>
            <ul class="dropdown-menu dropdown-menu-end shadow-none" aria-labelledby="navbarDropdown">
              <li><%= link_to t('navigation.profile'),
                              current_patient ? patient_path(current_patient)
                                : doctor_path(current_doctor),
                              class: 'dropdown-item' %></li>
              <li><%= link_to t('navigation.appointments'),
                              current_patient ? patient_appointments_path(current_patient)
                                : doctor_appointments_path(current_doctor),
                              class: 'dropdown-item' %></li>
              <% if current_doctor %>
                <li><%= link_to t('navigation.patients'),
                                doctor_patients_path(current_doctor),
                                class: 'dropdown-item' %></li>
              <% end %>
            </ul>
          </li>

          <li class="nav-item">
            <%= link_to current_patient ? destroy_patient_session_path : destroy_doctor_session_path,
                        method: :delete, class: 'nav-link' do %>
              <span class="oi oi-account-logout"></span> <%= t('navigation.logout') %>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('navigation.sign_up'), new_patient_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <span class="oi oi-account-login"></span> <%= t('navigation.login') %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end shadow-none" aria-labelledby="navbarDropdown">
              <li><%= link_to t('navigation.for_patients'), new_patient_session_path, class: 'dropdown-item' %></li>
              <li><%= link_to t('navigation.for_doctors'), new_doctor_session_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>