config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  devise_for :doctors, controllers: {
    sessions: 'doctors/sessions'
  }

  devise_for :patients, controllers: {
    registrations: 'patients/registrations',
    sessions: 'patients/sessions'
  }

  resources :patients, only: %i[show edit update] do
    resources :appointments, only: :index
  end

  resources :doctors, only: %i[show index] do
    resources :appointments do
      collection do
        get 'available_hours', to: 'appointments#available_hours'
      end
    end
    resources :patients, only: :index
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :delete_all
  has_many :doctors, through: :appointments
  has_one_attached :photo

  devise :database_authenticatable, :registerable, :validatable, authentication_keys: [:phone_number]

  enum gender: { male: 0, female: 1 }

  validates :phone_number, presence: true, uniqueness: true, length: { is: 9 }, numericality: true
  validates :first_name, presence: true, length: { maximum: 30 }
  validates :last_name, presence: true, length: { maximum: 30 }
  validates :patronymic, presence: true, length: { maximum: 30 }

  def full_name
    "#{last_name} #{first_name} #{patronymic}"
  end

  def age
    age = Date.today.year - birth_date.year
    age -= 1 if Date.today < birth_date + age.years
    age
  end

  def of?(doctor)
    doctors.exists?(doctor.id)
  end
end

app/controllers/patients/confirmations_controller.rb
# frozen_string_literal: true

class Patients::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/patients/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Patients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/patients/passwords_controller.rb
# frozen_string_literal: true

class Patients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/patients/registrations_controller.rb
# frozen_string_literal: true

class Patients::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email phone_number
                                                         first_name last_name patronymic])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/patients/sessions_controller.rb
# frozen_string_literal: true

class Patients::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/patients/unlocks_controller.rb
# frozen_string_literal: true

class Patients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  load_and_authorize_resource except: :index

  def index
    @doctor = Doctor.find(params[:doctor_id])

    if current_doctor == @doctor
      authorize! :index, current_doctor

      @patients = @doctor.patients

      respond_to do |format|
        format.html
      end
    else
      raise CanCan::AccessDenied.new(t('unauthorized.manage.all'), :index, Patient)
    end
  end

  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])

    if @patient.update(patient_params)
      redirect_to patient_path, notice: t('.success')
    else
      render action: 'edit'
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :patronymic, :gender, :birth_date, :photo)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_patient.html.erb
<tr>
  <th><%= link_to patient.id, patient_path(patient), class: 'link-primary' %></th>
  <td><%= link_to patient.full_name, patient_path(patient), class: 'link-primary text-decoration-none' %></td>
  <td><%= patient.gender ? t("gender.#{patient.gender}") : t('profile.unspecified') %></td>
  <td><%= patient.birth_date ? l(@patient.birth_date, format: :long) : t('profile.unspecified') %></td>
</tr>

app/views/patients/_small.html.erb
<div class="d-flex align-items-center mb-3">
  <%= photo_or_placeholder(patient, 50, 50, 'thumb-photo') %>
  <div class="d-flex flex-column ms-2">
    <%= link_to patient.full_name, patient_path(patient), class: 'link-primary text-decoration-none' %>
  </div>
</div>

app/views/patients/edit.html.erb
<%= content_for :title, t(".edit") %>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h2 class="text-center mb-4"><%= t(".edit") %></h2>

    <%= form_for @patient do |f| %>
      <%= render 'shared/error_messages', resource: @patient %>
      <div class="row g-3">
        <div class="col-md-4">
          <%= f.label :last_name, class: 'form-label' %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>

        <div class="col-md-4">
          <%= f.label :first_name, class: 'form-label' %>
          <%= f.text_field :first_name, autocomplete: 'first_name', class: 'form-control' %>
        </div>

        <div class="col-md-4">
          <%= f.label :patronymic, class: 'form-label' %>
          <%= f.text_field :patronymic, class: 'form-control' %>
        </div>

        <div class="col-12">
          <%= f.label :birth_date, class: 'form-label' %>
          <%= f.date_field :birth_date, class: 'form-control', max: Date.today %>
        </div>

        <div class="col-12">
          <div class="row">
            <div class="col-md-2">
              <%= f.label :gender, class: 'form-label' %>
            </div>
            <div class="col-md-10">
              <div class="form-check form-check-inline">
                <%= f.radio_button :gender, 'male', class: 'form-check-input' %>
                <%= f.label t('gender.male'), class: 'form-check-label', options: { for: 'genderMaleRadio' } %>
              </div>
              <div class="form-check form-check-inline">
                <%= f.radio_button :gender, 'female', class: 'form-check-input' %>
                <%= f.label t('gender.female'), class: 'form-check-label', options: { for: 'genderFemaleRadio' } %>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12">
          <%= f.label :photo, class: 'form-label' %>
          <%= f.file_field :photo, accept: 'image/png, image/gif, image/jpeg', direct_upload: true, class: 'form-control' %>
        </div>

        <div class="actions text-center">
          <%= f.submit t('.edit_btn'), class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/patients/index.html.erb
<%= content_for :title, t('.patients') %>

<div class="mx-5">
  <h2>
    <%= t('.patients') %>
    <%= link_to @doctor.full_name, doctor_path(@doctor), class: 'link-primary text-decoration-none' %>
  </h2>

  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= t('activerecord.attributes.appointment.patient') %></th>
      <th scope="col"><%= t('activerecord.attributes.patient.birth_date') %></th>
      <th scope="col"><%= t('activerecord.attributes.patient.gender') %></th>
    </tr>
    </thead>
    <%= render @patients %>
  </table>
</div>

app/views/patients/show.html.erb
<%= content_for :title, @patient.full_name %>

<div class="row">
  <div class="col-md-4 offset-md-2">
    <%= photo_or_placeholder(@patient, 300, 300, 'img-thumbnail') %>
  </div>
  <div class="col-md-6">
    <h3><%= @patient.full_name %></h3>
    <p>
      <span class="fw-bold"><%= t('activerecord.attributes.patient.birth_date') %>:</span>
      <% if @patient.birth_date %>
        <%= l @patient.birth_date, format: :long %>
      <% else %>
        <span class="text-muted"><%= t('profile.unspecified') %></span>
      <% end %>
    </p>
    <p>
      <span class="fw-bold"><%= t('activerecord.attributes.patient.gender') %>:</span>
      <% if @patient.gender %>
        <span><%= t("gender.#{@patient.gender}") %></span>
      <% else %>
        <span class="text-muted"><%= t('profile.unspecified') %></span>
      <% end %>
    </p>

    <p>
      <span class="oi oi-phone me-2"></span> <%= number_to_phone(@patient.phone_number, country_code: 380) %>
    </p>

    <%= link_to t('profile.edit'), edit_patient_path, class: 'btn btn-primary', role: 'button' if current_patient %>
    <%= link_to t('appointments.index.all_appointments'), patient_appointments_path(@patient), class: 'btn btn-outline-primary', role: 'button' %>
  </div>
</div>