config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  devise_for :doctors, controllers: {
    sessions: 'doctors/sessions'
  }

  devise_for :patients, controllers: {
    registrations: 'patients/registrations',
    sessions: 'patients/sessions'
  }

  resources :patients, only: %i[show edit update] do
    resources :appointments, only: :index
  end

  resources :doctors, only: %i[show index] do
    resources :appointments do
      collection do
        get 'available_hours', to: 'appointments#available_hours'
      end
    end
    resources :patients, only: :index
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :category
  has_many :appointments, dependent: :delete_all
  has_many :patients, through: :appointments
  has_one_attached :photo

  devise :database_authenticatable, :validatable, :validatable, authentication_keys: [:phone_number]

  validates :phone_number, presence: true, uniqueness: true, length: { is: 9 }, numericality: true
  validates :first_name, presence: true, length: { maximum: 30 }
  validates :last_name, presence: true, length: { maximum: 30 }
  validates :patronymic, presence: true, length: { maximum: 30 }
  validates_associated :category

  def full_name
    "#{last_name} #{first_name} #{patronymic}"
  end

  def available?
    appointments.active.count < 10
  end
end

app/controllers/doctors/confirmations_controller.rb
# frozen_string_literal: true

class Doctors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/doctors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Doctors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/doctors/passwords_controller.rb
# frozen_string_literal: true

class Doctors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/doctors/registrations_controller.rb
# frozen_string_literal: true

class Doctors::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors/sessions_controller.rb
# frozen_string_literal: true

class Doctors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/doctors/unlocks_controller.rb
# frozen_string_literal: true

class Doctors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  load_and_authorize_resource

  def index
    if params.key?(:category_id)
      doctors_by_category
    else
      @doctor = Doctor.all

      respond_to do |format|
        format.html
      end
    end
  end

  def show
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  private

  def doctors_by_category
    @doctors = params[:category_id].blank? ? Doctor.all : Doctor.where(category_id: params[:category_id])

    respond_to do |format|
      format.js { render layout: false }
    end
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_doctor.html.erb
<div class="d-flex py-3 align-items-center border-bottom">
  <div class="me-3">
    <%= link_to photo_or_placeholder(doctor, 100, 100, 'thumb-photo'), doctor_path(doctor) %>
  </div>

  <div class="flex-grow-1">
    <h3><%= link_to doctor.full_name, doctor_path(doctor), class: 'link-primary text-decoration-none' %></h3>
    <p class="mb-0 text-muted"><%= doctor.category.title %></p>
  </div>

  <%= link_to(t('shared.make_an_appointment'), new_doctor_appointment_path(doctor),
              class: 'btn btn-outline-primary', type: 'button') unless current_doctor || !doctor.available? %>
</div>

app/views/doctors/_small.html.erb
<div class="d-flex align-items-center mb-3">
  <%= photo_or_placeholder(doctor, 50, 50, 'thumb-photo') %>
  <div class="d-flex flex-column ms-2">
    <%= link_to doctor.full_name, doctor_path(doctor), class: 'link-primary text-decoration-none' %>
    <span class="text-muted"><%= doctor.category.title %></span>
  </div>
</div>

app/views/doctors/doctors_by_category.js.erb
document.querySelector('#doctors').innerHTML = "";

<% @doctors.each do |doctor| %>
  document.querySelector('#doctors').insertAdjacentHTML('beforeend', '<%= j render partial: doctor, locals: { doctor: doctor } %>');
<% end %>

app/views/doctors/index.html.erb
<%= content_for :title, t('navigation.doctors') %>

<div class="col-md-8 offset-md-2">
  <div class="mb-4">
    <%= select("categories", "category_id", Category.all.collect { |p| [p.title, p.id] },
               { include_blank: t('doctors.index.select_category') }, class: 'form-select category-select') %>
  </div>
  <div id="doctors">
    <%= render @doctors %>
  </div>
</div>

<%= javascript_pack_tag 'doctors' %>

app/views/doctors/index.js.erb
document.querySelector('#doctors').innerHTML = "";

<% @doctors.each do |doctor| %>
  document.querySelector('#doctors').insertAdjacentHTML('beforeend', '<%= j render partial: doctor, locals: { doctor: doctor } %>');
<% end %>

app/views/doctors/show.html.erb
<%= content_for :title, @doctor.full_name %>

<div class="row">
  <div class="col-md-4 offset-md-2">
    <%= photo_or_placeholder(@doctor, 300, 300, 'img-thumbnail') %>
  </div>

  <div class="col-md-6">
    <h3><%= @doctor.full_name %></h3>
    <h5 class="mb-3 text-muted"><%= @doctor.category.title %></h5>

    <p>
      <span class="oi oi-envelope-open me-2"></span><%= mail_to @doctor.email %>
    </p>

    <p>
      <span class="oi oi-phone me-2"></span> <%= number_to_phone(@doctor.phone_number, country_code: 380) %>
    </p>

    <% if current_patient %>
      <% if @doctor.available? %>
        <%= link_to t('shared.make_an_appointment'), new_doctor_appointment_path(@doctor), class: 'btn btn-primary' %>
      <% else %>
        <h5 class="text-danger"><%= t('.busy') %></h5>
      <% end %>
      <%= link_to t('appointments.index.all_appointments'), doctor_appointments_path(@doctor), class: 'btn btn-outline-success' if current_patient.of?(@doctor) %>
    <% end %>
  </div>
</div>