config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  devise_for :doctors, controllers: {
    sessions: 'doctors/sessions'
  }

  devise_for :patients, controllers: {
    registrations: 'patients/registrations',
    sessions: 'patients/sessions'
  }

  resources :patients, only: %i[show edit update] do
    resources :appointments, only: :index
  end

  resources :doctors, only: %i[show index] do
    resources :appointments do
      collection do
        get 'available_hours', to: 'appointments#available_hours'
      end
    end
    resources :patients, only: :index
  end
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor

  paginates_per 15

  default_scope -> { order datetime: :desc }
  scope :active, -> { where(active: true) }

  validates :datetime, presence: true
  validate :valid_date

  def status
    if closed?
      'closed'
    elsif past?
      'past'
    else
      'active'
    end
  end

  def past?
    datetime < DateTime.now.beginning_of_day
  end

  def closed?
    !active
  end

  private

  def valid_date
    errors.add(:datetime, :wrong_time) if datetime.hour < 9 || datetime.hour > 17
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource except: :index

  before_action :fix_params, only: :create

  rescue_from CanCan::AccessDenied do
    respond_to do |format|
      format.html do
        redirect_to new_patient_session_path
      end
    end
  end

  def index
    params.key?(:doctor_id) ? appointments_for_doctor : appointments_for_patient

    @appointments = @appointments.page(params[:page])

    respond_to do |format|
      format.html
    end
  end

  def show
    @doctor = Doctor.find(params[:doctor_id])
    @appointment = @doctor.appointments.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @doctor = Doctor.find(params[:doctor_id])
    ensure_doctor_availability

    @appointment = @doctor.appointments.new(patient_id: current_patient.id)

    respond_to do |format|
      format.html
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def update
    @appointment = Appointment.find(params[:id])
    @appointment.update(appointment_params.merge(active: false))

    respond_to do |format|
      format.html { redirect_to doctor_appointment_path }
    end
  end

  def create
    @doctor = Doctor.find(params[:doctor_id])
    ensure_doctor_availability

    @appointment = @doctor.appointments.create(patient_id: current_patient.id, datetime: appointment_params[:datetime])

    respond_to do |format|
      format.html { redirect_to doctor_appointment_path(@doctor, @appointment), notice: t('.created') }
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.delete

    respond_to do |format|
      format.html { redirect_to root_path, notice: t('.deleted') }
    end
  end

  def available_hours
    @doctor = Doctor.find(params[:doctor_id])

    date = DateTime.parse(params[:date])

    busy_hours = @doctor.appointments.active.where(datetime: date.all_day).collect { |d| d.datetime.hour }
    working_hours = (9..17).to_a
    @available_hours = working_hours - busy_hours

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:datetime, :recommendations)
  end

  def fix_params
    date = params[:appointment].delete(:date)
    hour = params[:appointment].delete(:hour).to_i
    datetime = DateTime.parse(date).change(hour: hour)

    params[:appointment][:datetime] = datetime
  end

  def ensure_doctor_availability
    unless @doctor.available?
      respond_to do |format|
        format.html { redirect_to doctors_path, flash: { danger: t('doctors.show.busy') } }
      end
    end
  end

  def appointments_for_doctor
    @doctor = Doctor.find(params[:doctor_id])

    if current_patient && current_patient.of?(@doctor)
      # Show patient all their appointments with selected doctor
      @appointments = @doctor.appointments.where(patient_id: current_patient.id)
    elsif @doctor == current_doctor
      # Show doctor only their own appointments
      @appointments = @doctor.appointments
    else
      raise CanCan::AccessDenied, t('unauthorized.manage.all')
    end
  end

  def appointments_for_patient
    @patient = Patient.find(params[:patient_id])

    if current_doctor && @patient.of?(current_doctor)
      # Show doctor all their appointments with selected patient
      @appointments = @patient.appointments.where(doctor_id: current_doctor.id)
    elsif @patient == current_patient
      # Show patient only their own appointments
      @appointments = @patient.appointments
    else
      raise CanCan::AccessDenied, t('unauthorized.manage.all')
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def time_options(available_hours)
    available_hours.map do |hour|
      tag_builder.content_tag_string(:option, "#{hour}:00 - #{hour + 1}:00", { value: hour })
    end.join('\n').html_safe
  end

  def datetime(appointment)
    l(appointment.datetime, format: '%d %B, %Y') + " #{appointment.datetime.hour}:00 - #{appointment.datetime.hour + 1}:00"
  end

  def pill_with_status(appointment)
    status = appointment.status

    class_name = if appointment.closed?
                   'secondary'
                 elsif appointment.past?
                   'danger'
                 else
                   'success'
                 end

    content_tag(:span, t("appointments.status.#{status}"), class: "badge bg-#{class_name}")
  end
end

app/views/appointments/_appointment.html.erb
<tr>
  <th><%= link_to appointment.id, doctor_appointment_path(appointment.doctor, appointment), class: 'link-primary' %></th>
  <td><%= link_to appointment.doctor.full_name, doctor_path(appointment.doctor), class: 'link-primary text-decoration-none' %></td>
  <td><%= link_to appointment.patient.full_name, patient_path(appointment.patient), class: 'link-primary text-decoration-none' %></td>
  <td><%= datetime(appointment) %></td>
  <td><%= pill_with_status(appointment) %></td>
  <th><%= link_to t('appointments.index.details'), doctor_appointment_path(appointment.doctor, appointment), class: 'link-primary' %></th>
</tr>

app/views/appointments/available_hours.js.erb
document.body.querySelector('.appointment-form select').innerHTML  = "<%= j time_options(@available_hours) %>";
document.body.querySelector('.appointment-form select').disabled = false;
document.body.querySelector('.appointment-form input[type=submit]').disabled = false;

app/views/appointments/edit.html.erb
<%= content_for :title, t('.header') %>

<div class="col-md-8 offset-md-2">
  <h2 class="mb-3">
    <%= t('.header') %>
    №<%= link_to @appointment.id, doctor_appointment_path(@appointment.doctor, @appointment) %>
  </h2>

  <%= form_for [@appointment.doctor, @appointment] do |f| %>
    <div class="mb-3">
      <%= f.text_area :recommendations, class: 'form-control' %>
    </div>

    <div class="actions text-center">
      <%= f.submit t('.save'), class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/appointments/index.html.erb
<%= content_for :title, t('.all_appointments') %>

<div class="mx-5">
  <h2>
    <%= t('.all_appointments') %>
    <% if current_patient %>
      <%= t('.patients') %>
      <%= link_to current_patient.full_name, patient_path(current_patient), class: 'link-primary text-decoration-none' %>
      <% if @doctor %>
        <%= t('.from_doctor') %>
        <%= link_to @doctor.full_name, doctor_path(@doctor), class: 'link-primary text-decoration-none' %>
      <% end %>
    <% elsif current_doctor %>
      <%= t('.doctors') %>
      <%= link_to current_doctor.full_name, doctor_path(current_doctor), class: 'link-primary text-decoration-none' %>
      <% if @patient %>
        <%= t('.from_patient') %>
        <%= link_to @patient.full_name, patient_path(@patient), class: 'link-primary text-decoration-none' %>
      <% end %>
    <% end %>
  </h2>

  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= t('activerecord.attributes.appointment.doctor') %></th>
      <th scope="col"><%= t('activerecord.attributes.appointment.patient') %></th>
      <th scope="col"><%= t('activerecord.attributes.appointment.datetime') %></th>
      <th scope="col"><%= t('activerecord.attributes.appointment.active') %></th>
      <th scope=""></th>
    </tr>
    </thead>
    <%= render @appointments %>
  </table>

  <div class="d-flex justify-content-center">
    <%= paginate @appointments %>
  </div>
</div>

app/views/appointments/new.html.erb
<%= content_for :title, t('appointments.new.header') %>

<div class="col-md-8 offset-md-2">
  <h2 div class="mb-3"> <%= t('appointments.new.header') %> <%= link_to @doctor.full_name, doctor_path(@doctor), class: 'link-primary text-decoration-none' %></h2>
  <%= form_with model: [@doctor, @appointment],
                method: 'post', local: true,
                class: 'appointment-form',
                data: { doctor_id: @doctor.id } do |f| %>
    <div class="row">
      <div class="col-md-8">
        <%= f.date_field :date, class: 'form-control date-selector', min: Date.tomorrow %>
      </div>
      <div class="col-md-4">
        <select class="form-select" name="appointment[hour]" disabled>
          <option selected value>Выберите время</option>
        </select>
      </div>
    </div>
    <div class="actions text-center mt-3">
      <%= f.submit t('shared.make_an_appointment'), class: 'btn btn-primary', disabled: true %>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag 'appointments' %>

app/views/appointments/show.html.erb
<%= content_for :title, t('.appointment_details') %>

<div class="col-md-8 offset-md-2">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2><%= t('.appointment', id: @appointment.id) %></h2>
    <%= pill_with_status(@appointment) %>
  </div>

  <p><b><%= t('activerecord.attributes.appointment.datetime') %>:</b> <%= datetime(@appointment) %></p>

  <div class="row">
    <div class="col-md-6">
      <p><b><%= t('activerecord.models.doctor') %>:</b> </p>
      <%= render partial: 'doctors/small', locals: { doctor: @doctor } %>
    </div>
    <div class="col-md-6">
      <p><b><%= t('activerecord.models.patient') %>:</b> </p>
      <%= render partial: 'patients/small', locals: { patient: @appointment.patient } %>
    </div>
  </div>

  <p><b><%= t('activerecord.attributes.appointment.recommendations') %>:</b>
    <% if @appointment.recommendations.blank? %>
    <p class="text-muted">
      <% if current_patient %>
        <%= t('.blank_recommendations.for_patient') %>
      <% else %>
        <%= t('.blank_recommendations.for_doctor') %>
      <% end %>
    </p>
  <% else %>
    <p><%= @appointment.recommendations %></p>
  <% end %>
  </p>
  <% if @appointment.active? %>
    <%= link_to t('.cancel_appointment'), doctor_appointment_path,
                class: 'btn btn-danger', type: 'button', method: :delete if current_patient && @appointment.active? %>

    <%= link_to t('.edit_recommendations'), edit_doctor_appointment_path,
                class: 'btn btn-outline-primary', type: 'button' if current_doctor && @appointment.past? %>
  <% end %>
</div>